services:
  challenge_web:
    build: . # Constrói a imagem a partir do Dockerfile na pasta atual (.)
    container_name: challenge_web 
    command: python manage.py runserver 0.0.0.0:8000 # Comando para iniciar o servidor Django
    volumes:
      - ./app:/app
    ports:
      - "8000:8000" 
    env_file:
      - .env 
    depends_on:
      - challenge_db # Diz ao Docker para iniciar o banco de dados ANTES da aplicação web
  challenge_db:
    image: postgres:13 
    container_name: challenge_db 
    volumes:
      - postgres_data:/var/lib/postgresql/data/ # Garante que os dados do banco não se percam ao reiniciar o contêiner
    environment: 
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
  challenge_n8n:
    image: n8nio/n8n 
    container_name: challenge_n8n 
    ports:
      - "5678:5678" 
    volumes:
      - n8n_data:/home/node/.n8n 

volumes:
  postgres_data:
  n8n_data:
