# Generated by Django 4.2.23 on 2025-08-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='empresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NOVO', 'Novo'), ('EM_CONTATO', 'Em Contato'), ('CONVERTIDO', 'Convertido'), ('PERDIDO', 'Perdido')], default='NOVO', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
